name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: 0 0 * * *

jobs:
  build:

    # runs-on: ubuntu-latest
    # # container:
    # #   image: ruby:2.6.5
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        ruby: [ 2.4, 2.5, 2.6, 2.7, jruby, truffleruby ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}

    # steps:
    # - uses: actions/checkout@v2
    # - uses: ruby/setup-ruby@v1
    #   with:
    #     ruby-version: 2.6

    - name: Set up node and yarn
      run: |
        curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
        echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
        curl -sL https://deb.nodesource.com/setup_12.x | bash -
        apt install -y nodejs yarn
    - name: Build and setup
      run: |
        bundle -j 4
        bin/setup
    - name: Install chrome
      run: |
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
        echo 'deb http://dl.google.com/linux/chrome/deb/ stable main' | tee /etc/apt/sources.list.d/google-chrome.list
        apt update -y
        apt install -y google-chrome-stable
    - name: Rubocop
      run: |
        bundle exec rubocop ./rubocop.yml --parallel
    - name: Lint
      run: |
        bundle exec slim-lint app/views -c config/slim_lint.yml
        bin/yarn eslint app/javascript
        bin/yarn eslint test/javascript
    - name: Test
      run: |
        bundle exec rails test && bundle exec rails test:system
        yarn test
